name: 'ClassifierFreeDiffRoll'
args:
    residual_channels: 512
    unconditional: False
    condition: 'fixed' # either trainable_spec or trainable_z, or fixed
    n_mels: ${spec.args.n_mels}
    residual_layers: 15
    kernel_size: 3
    dilation_base: 2
    dilation_bound: 4
    spec_dropout: 0.1
    norm_args:
    - 0
    - 1
    - 'imagewise'    