gpus: 1
val_freq: 5
hop_length: 512
sequence_length: 327680
sampling_rate: 16000
min_midi: 21
max_midi: 108
learning_rate: 1e-5
epochs: 200
download: False
data_root: './dataset'

dataset:
    train:
        root: ${data_root} 
        groups: 'train'            
        download: ${download}
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000    
    val:
        root: ${data_root} 
        groups: 'validation'            
        download: False
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000
        
    test:
        root: ${data_root} 
        groups: 'test'            
        download: False
        preload: False
        sequence_length: ${sequence_length}
        seed: 42
        hop_length: ${hop_length}
        max_midi: 108
        min_midi: 21
        ext_audio: '.wav'
        sampling_rate: 16000
        
dataloader:
    train:
        batch_size: 16
        num_workers: 8
        shuffle: True
        pin_memory: True
    valid:
        batch_size: 16
        num_workers: 8
        shuffle: False
        pin_memory: True
    test:
        batch_size: 4
        num_workers: 8
        shuffle: False
        pin_memory: True
        
model:
    dim: 28
    channels: 1
        
trainer:
    gpus: ${gpus}
    max_epochs: ${epochs}
    check_val_every_n_epoch: ${val_freq}
    
task:
    lr: ${learning_rate}
    timesteps: 200
    loss_type: 'huber'

# defaults:    
#     - spec_layer: Mel
#     - model: CNN_LSTM