gpus: 1
val_freq: 5
hop_length: 512
sequence_length: 327680 # 20 sec data. This is fixed for matching with the test phase.
sampling_rate: 16000
min_midi: 21
max_midi: 108
learning_rate: 1e-5
epochs: 2500
download: False

#Place your directory path containing MAESTRO v2.0.0. e.g. system_root/Documents/data/
data_root: path/to/training/data/MAESTROv2.0.0
pin_memory: True


dataloader:
    train:
        batch_size: 16
        num_workers: 40
        shuffle: True
        pin_memory: ${pin_memory}
        prefetch_factor: 2
        persistent_workers: True
    val:
        batch_size: 16
        num_workers: 4
        shuffle: False
        pin_memory: ${pin_memory}
    test:
        batch_size: 4
        num_workers: 4
        shuffle: False
        pin_memory: ${pin_memory}
        
        
trainer:
    gpus: ${gpus}
    max_epochs: ${epochs}
    check_val_every_n_epoch: ${val_freq}
    
modelcheckpoint:
    monitor: 'Val/diffusion_loss'
    filename: '{epoch:02d}e-diffusion_loss{Train/diffusion_loss:.2f}'
    save_top_k: 2
    save_last: True
    mode: "min"
    auto_insert_metric_name: False    
    


defaults:
    - spec: mel
    - model: ClassifierFreeDiffRoll
    - task: classifierfree_diffusion
    - dataset: MAESTRO