name1: 'MAPS'
name2: 'MAESTRO'
train1:
    root: ${data_root} 
    groups: 'train'
    data_type: 'MUS'
    download: ${download}
    preload: False
    sequence_length: ${sequence_length}
    seed: 42
    hop_length: ${hop_length}
    max_midi: 108
    min_midi: 21
    ext_audio: '.wav'
    sampling_rate: 16000
    overlap: False

train2:
    root: ${data_root} 
    groups: 'train'            
    download: ${download}
    preload: False
    sequence_length: ${sequence_length}
    seed: 42
    hop_length: ${hop_length}
    max_midi: 108
    min_midi: 21
    ext_audio: '.wav'
    sampling_rate: 16000 

val1:
    root: ${data_root} 
    groups: 'test'
    data_type: 'MUS'
    download: ${download}
    preload: False
    sequence_length: ${sequence_length}
    seed: 42
    hop_length: ${hop_length}
    max_midi: 108
    min_midi: 21
    ext_audio: '.wav'
    sampling_rate: 16000
    overlap: True
val2:
    root: ${data_root} 
    groups: 'validation'            
    download: ${download}
    preload: False
    sequence_length: ${sequence_length}
    seed: 42
    hop_length: ${hop_length}
    max_midi: 108
    min_midi: 21
    ext_audio: '.wav'
    sampling_rate: 16000 

test:
    root: ${data_root} 
    groups: 'test'
    data_type: 'MUS'
    download: False
    preload: False
    sequence_length: ${sequence_length}
    seed: 42
    hop_length: ${hop_length}
    max_midi: 108
    min_midi: 21
    ext_audio: '.wav'
    sampling_rate: 16000
    overlap: True